// State information including name, zip prefix, and timezone
const statesData = {
    AL: { name: "Alabama", zipPrefix: "35", timezone: "America/Chicago" },
    AK: { name: "Alaska", zipPrefix: "99", timezone: "America/Anchorage" },
    AZ: { name: "Arizona", zipPrefix: "85", timezone: "America/Phoenix" },
    AR: { name: "Arkansas", zipPrefix: "71", timezone: "America/Chicago" },
    CA: { name: "California", zipPrefix: "90", timezone: "America/Los_Angeles" },
    CO: { name: "Colorado", zipPrefix: "80", timezone: "America/Denver" },
    CT: { name: "Connecticut", zipPrefix: "06", timezone: "America/New_York" },
    DE: { name: "Delaware", zipPrefix: "19", timezone: "America/New_York" },
    FL: { name: "Florida", zipPrefix: "32", timezone: "America/New_York" },
    GA: { name: "Georgia", zipPrefix: "30", timezone: "America/New_York" },
    HI: { name: "Hawaii", zipPrefix: "96", timezone: "Pacific/Honolulu" },
    ID: { name: "Idaho", zipPrefix: "83", timezone: "America/Boise" },
    IL: { name: "Illinois", zipPrefix: "60", timezone: "America/Chicago" },
    IN: { name: "Indiana", zipPrefix: "46", timezone: "America/Indiana/Indianapolis" },
    IA: { name: "Iowa", zipPrefix: "50", timezone: "America/Chicago" },
    KS: { name: "Kansas", zipPrefix: "66", timezone: "America/Chicago" },
    KY: { name: "Kentucky", zipPrefix: "40", timezone: "America/New_York" },
    LA: { name: "Louisiana", zipPrefix: "70", timezone: "America/Chicago" },
    ME: { name: "Maine", zipPrefix: "04", timezone: "America/New_York" },
    MD: { name: "Maryland", zipPrefix: "20", timezone: "America/New_York" },
    MA: { name: "Massachusetts", zipPrefix: "01", timezone: "America/New_York" },
    MI: { name: "Michigan", zipPrefix: "48", timezone: "America/Detroit" },
    MN: { name: "Minnesota", zipPrefix: "55", timezone: "America/Chicago" },
    MS: { name: "Mississippi", zipPrefix: "38", timezone: "America/Chicago" },
    MO: { name: "Missouri", zipPrefix: "63", timezone: "America/Chicago" },
    MT: { name: "Montana", zipPrefix: "59", timezone: "America/Denver" },
    NE: { name: "Nebraska", zipPrefix: "68", timezone: "America/Chicago" },
    NV: { name: "Nevada", zipPrefix: "89", timezone: "America/Los_Angeles" },
    NH: { name: "New Hampshire", zipPrefix: "03", timezone: "America/New_York" },
    NJ: { name: "New Jersey", zipPrefix: "07", timezone: "America/New_York" },
    NM: { name: "New Mexico", zipPrefix: "87", timezone: "America/Denver" },
    NY: { name: "New York", zipPrefix: "10", timezone: "America/New_York" },
    NC: { name: "North Carolina", zipPrefix: "27", timezone: "America/New_York" },
    ND: { name: "North Dakota", zipPrefix: "58", timezone: "America/Chicago" },
    OH: { name: "Ohio", zipPrefix: "43", timezone: "America/New_York" },
    OK: { name: "Oklahoma", zipPrefix: "73", timezone: "America/Chicago" },
    OR: { name: "Oregon", zipPrefix: "97", timezone: "America/Los_Angeles" },
    PA: { name: "Pennsylvania", zipPrefix: "15", timezone: "America/New_York" },
    RI: { name: "Rhode Island", zipPrefix: "02", timezone: "America/New_York" },
    SC: { name: "South Carolina", zipPrefix: "29", timezone: "America/New_York" },
    SD: { name: "South Dakota", zipPrefix: "57", timezone: "America/Chicago" },
    TN: { name: "Tennessee", zipPrefix: "37", timezone: "America/Chicago" },
    TX: { name: "Texas", zipPrefix: "75", timezone: "America/Chicago" },
    UT: { name: "Utah", zipPrefix: "84", timezone: "America/Denver" },
    VT: { name: "Vermont", zipPrefix: "05", timezone: "America/New_York" },
    VA: { name: "Virginia", zipPrefix: "20", timezone: "America/New_York" },
    WA: { name: "Washington", zipPrefix: "98", timezone: "America/Los_Angeles" },
    WV: { name: "West Virginia", zipPrefix: "24", timezone: "America/New_York" },
    WI: { name: "Wisconsin", zipPrefix: "53", timezone: "America/Chicago" },
    WY: { name: "Wyoming", zipPrefix: "82", timezone: "America/Denver" }
};
